wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.16.5
    framework: huggingface
    huggingface_version: 4.40.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716625371.0
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 75
      - 86
      - 95
      - 98
      - 105
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 75
      - 86
      - 92
      - 95
      - 98
      - 105
      3:
      - 2
      - 23
      - 37
      4: 3.11.7
      5: 0.16.5
      6: 4.40.1
      8:
      - 5
      13: linux-x86_64
Analysis_question:
  desc: null
  value: Which locations are at risk of evacuation?
Cross_Encoder_rerank:
  desc: null
  value: 'No'
LLM:
  desc: null
  value: Llama-3-8b-chat-hf
Retrieval_distance_metric:
  desc: null
  value: L2
Retrieval_type:
  desc: null
  value: Query
k:
  desc: null
  value: 30
